# This prompt file is added for adapting OpenRCA RCA-agent to AIOps Challenge telemetry.
# It is intentionally concise and aligned to the CSV schema generated by
# `AIOpsChallenge_Adapt/build_openrca_dataset_from_causalrca_pkls.py`.

cand = """## POSSIBLE ROOT CAUSE REASONS:

- timeout
- error
- latency
- traffic drop
- service degradation

## POSSIBLE ROOT CAUSE COMPONENTS:

- frontend
- adservice
- cartservice
- checkoutservice
- currencyservice
- emailservice
- paymentservice
- productcatalogservice
- recommendationservice
- shippingservice
- redis
"""

schema = f"""## TELEMETRY DIRECTORY STRUCTURE:

- You can access the telemetry directory in our microservices system: `dataset/AIOpsChallenge/phaseX/telemetry/`.

- Each anomaly case is stored in its own subdirectory named by `{{uuid}}` (e.g., `dataset/AIOpsChallenge/phase1/telemetry/345fbe93-80/`).

- Within each case directory, you’ll find these subdirectories: `metric`, `trace`, and `log`.

- The telemetry data in those subdirectories is stored in CSV format.

## DATA SCHEMA

1. **Metric Files**:

- `metric/metric_service.csv`:

	timestamp,cmdb_id,kpi_name,value
	1749101400,frontend,error_rate,0.0
	1749101400,cartservice,avg_duration,12.3

- `timestamp` is Unix seconds (UTC).
- `cmdb_id` is the service name (lowercase).
- `kpi_name` is one of: calls, avg_duration, error_rate, timeout_rate.

2. **Trace Files**:

- `trace/trace_span.csv` (may be empty):

	timestamp,cmdb_id,parent_id,span_id,trace_id,duration

3. **Log Files**:

- `log/log_service.csv` (may be empty):

	log_id,timestamp,cmdb_id,log_name,value

{cand}

## CLARIFICATION OF TELEMETRY DATA:

1. This microservice system is a containerized e-commerce application.
2. Use UTC+8 time zone in analysis if needed (telemetry timestamp is UTC seconds).
"""
# This prompt file is added for adapting OpenRCA RCA-agent to AIOps Challenge telemetry.
# It is intentionally concise and aligned to the CSV schema generated by
# `AIOpsChallenge_Adapt/build_openrca_dataset_from_causalrca_pkls.py`.

cand = """## POSSIBLE ROOT CAUSE REASONS:

- timeout
- error
- latency
- traffic drop
- service degradation